name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.6'

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      working-directory: ./pkg
      run: go build ./...

    - name: Test With Coverage
      working-directory: ./pkg
      run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./pkg

    - name: Run Vet & Lint
      working-directory: ./pkg
      run: |
        go vet ./...
        golint -set_exit_status=1 ./..


